<?php

use Illuminate\Database\Seeder;

class HousePropertySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('house_properties')->insert(
            [
                'name' => '不動産A',
                'type' => '賃貸',
                'good' => 'コンビニが近い',
                'bad' => '駅から遠い',
                'pet_type' => '猫',
                'nearest_station' => '東新宿駅',
                'address' => '東京都新宿区東新宿1-1-1',
                'is_pet' => '可',
                'cost' => '90000',
                'manage_cost' => '5000',
                'deposit' => '1ヶ月分',
                'key_money' => '1ヶ月分',
                'area' => '20',
                'floor_plan' => '1K',
                'floor' => '2',
                'age' => '1990-04',
                'structure' => '鉄筋コンクリート',
                'park' => '有',
                'facility' => '特になし',
                'corp' => 'テスト不動産',
            ]);
        DB::table('house_properties')->insert(
            [
                'name' => 'パーク池袋',
                'type' => '賃貸',
                'good' => '病院が近い',
                'bad' => '狭い',
                'pet_type' => '犬と猫',
                'nearest_station' => '池袋',
                'address' => '東京都豊島区池袋1-1-1',
                'is_pet' => '可',
                'cost' => '50000',
                'manage_cost' => '0',
                'deposit' => '1ヶ月分',
                'key_money' => '1ヶ月分',
                'area' => '15',
                'floor_plan' => '1K',
                'floor' => '8',
                'age' => '1970-04',
                'structure' => '鉄筋コンクリート',
                'park' => '無',
                'facility' => '風呂無しトイレ共同',
                'corp' => 'にゃんこ不動産',
            ]);
        DB::table('house_properties')->insert(
            [
                'name' => '板橋荘',
                'type' => '賃貸',
                'good' => '猫ちゃんに優しい',
                'bad' => '少し古い',
                'pet_type' => '猫',
                'nearest_station' => '下赤塚',
                'address' => '東京都板橋区下赤塚1-1-1',
                'is_pet' => '可',
                'cost' => '30000',
                'manage_cost' => '5000',
                'deposit' => '1ヶ月分',
                'key_money' => '1ヶ月分',
                'area' => '20',
                'floor_plan' => '1K',
                'floor' => '2',
                'age' => '1950-04',
                'structure' => '木造',
                'park' => '無',
                'facility' => '特になし',
                'corp' => 'にゃんこ不動産',
            ]);
        DB::table('house_properties')->insert(
            [
                'name' => 'ビビッド六本木',
                'type' => '賃貸',
                'good' => '最高級のタワーマンション',
                'bad' => '値段も階数も高い',
                'pet_type' => '犬',
                'nearest_station' => '六本木',
                'address' => '東京都港区六本木1-1-1',
                'is_pet' => '可',
                'cost' => '200000',
                'manage_cost' => '2000',
                'deposit' => '2ヶ月分',
                'key_money' => '2ヶ月分',
                'area' => '60',
                'floor_plan' => '3LDK',
                'floor' => '30',
                'age' => '2015-04',
                'structure' => '鉄筋コンクリート',
                'park' => '有',
                'facility' => '特になし',
                'corp' => 'わんこ不動産',
            ]);
        DB::table('house_properties')->insert(
            [
                'name' => '不動産B',
                'type' => '賃貸',
                'good' => 'コンビニが近い',
                'bad' => '駅から遠い',
                'pet_type' => '猫',
                'nearest_station' => '東新宿駅',
                'address' => '東京都新宿区東新宿1-1-1',
                'is_pet' => '可',
                'cost' => '90000',
                'manage_cost' => '5000',
                'deposit' => '1ヶ月分',
                'key_money' => '1ヶ月分',
                'area' => '20',
                'floor_plan' => '1K',
                'floor' => '2',
                'age' => '1990-04',
                'structure' => '鉄筋コンクリート',
                'park' => '有',
                'facility' => '特になし',
                'corp' => 'テスト不動産',
            ]);
        DB::table('house_properties')->insert(
            [
                'name' => '不動産C',
                'type' => '賃貸',
                'good' => 'コンビニが近い',
                'bad' => '駅から遠い',
                'pet_type' => '猫',
                'nearest_station' => '東新宿駅',
                'address' => '東京都新宿区東新宿1-1-1',
                'is_pet' => '可',
                'cost' => '90000',
                'manage_cost' => '5000',
                'deposit' => '1ヶ月分',
                'key_money' => '1ヶ月分',
                'area' => '20',
                'floor_plan' => '1K',
                'floor' => '2',
                'age' => '1990-04',
                'structure' => '鉄筋コンクリート',
                'park' => '有',
                'facility' => '特になし',
                'corp' => 'テスト不動産',
            ]);
        DB::table('house_properties')->insert(
            [
                'name' => '不動産D',
                'type' => '賃貸',
                'good' => 'コンビニが近い',
                'bad' => '駅から遠い',
                'pet_type' => '猫',
                'nearest_station' => '東新宿駅',
                'address' => '東京都新宿区東新宿1-1-1',
                'is_pet' => '可',
                'cost' => '90000',
                'manage_cost' => '5000',
                'deposit' => '1ヶ月分',
                'key_money' => '1ヶ月分',
                'area' => '20',
                'floor_plan' => '1K',
                'floor' => '2',
                'age' => '1990-04',
                'structure' => '鉄筋コンクリート',
                'park' => '有',
                'facility' => '特になし',
                'corp' => 'テスト不動産',
            ]);
        DB::table('house_properties')->insert(
            [
                'name' => '不動産E',
                'type' => '賃貸',
                'good' => 'コンビニが近い',
                'bad' => '駅から遠い',
                'pet_type' => '猫',
                'nearest_station' => '東新宿駅',
                'address' => '東京都新宿区東新宿1-1-1',
                'is_pet' => '可',
                'cost' => '90000',
                'manage_cost' => '5000',
                'deposit' => '1ヶ月分',
                'key_money' => '1ヶ月分',
                'area' => '20',
                'floor_plan' => '1K',
                'floor' => '2',
                'age' => '1990-04',
                'structure' => '鉄筋コンクリート',
                'park' => '有',
                'facility' => '特になし',
                'corp' => 'テスト不動産',
            ]);
        DB::table('house_properties')->insert(
            [
                'name' => '不動産F',
                'type' => '賃貸',
                'good' => 'コンビニが近い',
                'bad' => '駅から遠い',
                'pet_type' => '猫',
                'nearest_station' => '東新宿駅',
                'address' => '東京都新宿区東新宿1-1-1',
                'is_pet' => '可',
                'cost' => '90000',
                'manage_cost' => '5000',
                'deposit' => '1ヶ月分',
                'key_money' => '1ヶ月分',
                'area' => '20',
                'floor_plan' => '1K',
                'floor' => '2',
                'age' => '1990-04',
                'structure' => '鉄筋コンクリート',
                'park' => '有',
                'facility' => '特になし',
                'corp' => 'テスト不動産',
            ]);
        DB::table('house_properties')->insert(
            [
                'name' => '不動産G',
                'type' => '賃貸',
                'good' => 'コンビニが近い',
                'bad' => '駅から遠い',
                'pet_type' => '猫',
                'nearest_station' => '東新宿駅',
                'address' => '東京都新宿区東新宿1-1-1',
                'is_pet' => '可',
                'cost' => '90000',
                'manage_cost' => '5000',
                'deposit' => '1ヶ月分',
                'key_money' => '1ヶ月分',
                'area' => '20',
                'floor_plan' => '1K',
                'floor' => '2',
                'age' => '1990-04',
                'structure' => '鉄筋コンクリート',
                'park' => '有',
                'facility' => '特になし',
                'corp' => 'テスト不動産',
            ]);

    }
}
