<template>
    <div class="sidebar">
        <v-list
            class="pt-0"
        >
            <v-list-item
                class="mb-2"
            >
                <v-img
                    src="/images/side_banner.png"
                ></v-img>
            </v-list-item>
            <v-list-item
                class="my-2"
            >
                <v-img
                    src="/images/side_ouchi.png"
                ></v-img>
            </v-list-item>
            <v-list-item
                class="my-2"
                href="https://equall.jp"
                target="_blank"
            >
                <v-img
                    src="/images/side_kurashi.png"
                ></v-img>
            </v-list-item>
            <v-list-item
                class="my-2"
                href="https://media.equall.jp"
                target="_blank"
            >
                <v-img
                    src="/images/side_equalllife.png"
                ></v-img>
            </v-list-item>
        </v-list>
    </div>
</template>
